routes/web.php
<?php

use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::resource('task',TaskController::class);
    Route::get('task/{task}/done',[TaskController::class,'done'])->name('task.done');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'description',
        'user_id',
        'is_done'
    ];
    protected $casts = [
        'is_done'=>'boolean',
        'user_id'=>'integer',
        'created_at' => 'datetime:d/m/Y H:i:s',
        'updated_at' => 'datetime:d/m/Y H:i:s',
    ];

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tasks(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Task\CreateFormRequest;
use App\Http\Requests\Task\UpdateFormRequest;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = auth()->user()->tasks()->paginate(5);
        return view('tasks.index')
            ->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Task::class);
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateFormRequest $request)
    {
        Task::create($request->validated());
        return redirect()->route('task.index')
            ->with('success','Task Has Been Created');;
    }

    /**
     * Display the specified resource.
     *
     * @param  Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        $this->authorize('view', $task);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $this->authorize('update', $task);
        return view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFormRequest $request, Task $task)
    {
        $this->authorize('update', $task);
        $task->update($request->validated());
        return redirect()->route('task.index')
            ->with('success','Task Has Been Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $this->authorize('delete', $task);
        $task->delete();
        return redirect()->route('task.index')
            ->with('success','Task Has Been Deleted');;
    }
    /**
     * MArk as done the specified resource in storage.
     *
     * @param  Task  $task
     * @return \Illuminate\Http\Response
     */
    public function done(Task $task)
    {
        $this->authorize('update', $task);
        $task->update(['is_done' => true]);
        return redirect()->back()->with('success','Task Has Been Completed');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @include('layouts.partials._messages')
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/partials/_messages.blade.php
<div class="col-md-12">
    @if (session('success'))
        <div class="alert alert-success">
            <h5>Success !</h5>
            <p class="alert-message">{{ session('success') }}</p>
        </div>
    @endif
    @if (session('warning'))
        <div class="alert alert-warning">
            <h5>Alert !</h5>
            <p class="alert-message">{{ session('warning') }}</p>
        </div>
    @endif
        @if(count($errors)>0)
            <div class="alert alert-danger" role="alert">
                <h5>Attention</h5>
                @if(session('errors'))
                    <ul class="list-unstyled">
                        @foreach($errors->all() as $error)
                            <li class="alert-message">{{$error}}</li>
                        @endforeach
                    </ul>
                @endif
            </div>
        @endif
</div>

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-8 offset-2">
            <h4>New ToDo</h4>
            <form action="{{ route('task.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <a href="{{ route('task.index') }}" class="btn btn-warning">Cancel</a>
                    <button type="submit" class="btn btn-success">Create New</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-8 offset-2">
            <h4>Edit ToDo</h4>
            <form action="{{ route('task.update',$task) }}" method="POST">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control">{{ $task->description }}</textarea>
                </div>
                <div class="form-group">
                    <a href="{{ route('task.index') }}" class="btn btn-warning">Cancel</a>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="row">
        <div class="col-12">
            <h3>Tasks</h3>
            <p><a href="{{ route('task.create') }}" class="btn btn-sm btn-primary">Create new</a></p>
            <hr>
            <div class="row">
                <div class="col-8"><h4>Task</h4></div>
                <div class="col-4"><h4>Actions</h4></div>
            </div>
            @forelse ($tasks as $item)

                @include('tasks.list')
            @empty
                <div class="alert alert-info">No Any Tasks</div>
            @endforelse
            {{ $tasks->links() }}
        </div>
    </div>
@endsection

resources/views/tasks/list.blade.php
<div class="row mb-4">
    <div class="col-8">

        @if($item->is_done)
            <s>{{ $item->description }}</s>
        @else
            {{ $item->description }}
        @endif

    </div>
    <div class="col-4">
        <div class="btn-group">
            <a href="{{ route('task.edit',$item) }}" class="btn btn-sm btn-info mr-2">Edit</a>
            @if($item->is_done)
            <button class="btn btn-success btn-sm" disabled>Done</button>
            @else
                <a href="{{ route('task.done',$item) }}" class="btn btn-warning btn-sm">Done</a>
            @endif
            <form action="{{ route('task.destroy',$item) }}" class="ml-2" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" name="delete" class="btn btn-sm btn-danger">Delete</button>
            </form>
        </div>
    </div>
</div>